### ISSUE TITLE
usage guide

### ISSUE THREAD

**Issue by nitin456** [linkedin/kafka-tools#105]
@toddpalino 
I need to do partition rebalancing in rackaware mode. Can you please help me with the  command for that? I was not able to find any usage guide.

**Comment by pcn** [comment]
@nitin456 have you looked at the [wiki docs](https://github.com/linkedin/kafka-tools/wiki/Kafka-Assigner)?

**Comment by nitin456** [comment]
Yes, I checked. I was running below command to get rackaware balancing  but it is throwing error.

kafka-assigner  --zookeeper  someZookeeperString --tools-path someKafkaToolPath balance -t rackaware

Error:   File "/usr/local/lib/python2.7/dist-packages/kafka/tools/assigner/actions/balancemodules/rackaware.py", line 133, in _try_pick_new_broker
    pos))
kafka.tools.exceptions.BalanceException: Cannot find a swap for broker 14 on partition __consumer_offsets:0 at position 0

**Comment by nitin456** [comment]
Closing this issue as it has nothing to do with usage guide.
