### ISSUE TITLE
Simplify using Kafka admin commands (jar files)

### ISSUE THREAD

**Issue by bringhurst** [linkedin/kafka-tools#32]
The problem here is that there's a confusing step in getting kafka-tools working -- installing the Kafka admin command jar files. We should hide this from users as much as possible.

I'm not sure how this should be fixed. Here's a few options:

- If the Kafka admin jar files are not available, the user should be asked if the files should be downloaded and installed for them (perhaps to their home directory?).
- The Kafka admin jar files should be packaged at build time and included as package_resources. This seems like the best option from the users' point of view, but could harm build stability.
- kafka-tools should simply just scan a list of known locations and error out if it can't find them. It should then perhaps prompt the user that they need to run some command (e.g. yum install kafka-server).

**Comment by toddpalino** [comment]
So the tool already searches known locations (PATH) for the tools and errors out if it can't find them. I'm not sure about the idea of adding the JAR files into the build, though, as my concern is that we will run into versioning problems with the Kafka cluster itself if the tools are incompatible.

**Comment by bringhurst** [comment]
> we will run into versioning problems with the Kafka cluster itself if the tools are incompatible

Agreed. This is a problem with Kafka itself since the admin tools blindly assume that they're connecting to a broker with the same version instead of checking if the versions match.

Since fixing the admin tools is way out of the scope of this project, I'm going to close this issue and consider it blocked. Folks will need to just manually deal with having a copy of the admin tools that match the version of the broker they're running (the current behavior)

If anyone finds that the admin tools have been updated to safely check the version of the brokers they connect to, feel free to reopen this.
