### ISSUE TITLE
balancing by size fails with IndexError: list index out of range

### ISSUE THREAD

**Issue by mwol** [linkedin/kafka-tools#47]
Sometime balancing by size fails due to an IndexError: list index out of range:

`INFO] Starting partition balance by size
Traceback (most recent call last):
  File "/usr/local/bin/kafka-assigner", line 9, in <module>
    load_entry_point('kafka-tools==0.0.2', 'console_scripts', 'kafka-assigner')()
  File "/usr/local/lib/python2.7/dist-packages/kafka/tools/assigner/__main__.py", line 100, in main
    action_to_run.process_cluster()
  File "/usr/local/lib/python2.7/dist-packages/kafka/tools/assigner/actions/balance.py", line 47, in process_cluster
    bmodule.process_cluster()
  File "/usr/local/lib/python2.7/dist-packages/kafka/tools/assigner/actions/balancemodules/size.py", line 61, in process_cluster
    margins[pos] = (partitions[pos][sizelen // 2].size + partitions[pos][sizelen // 2 - 1].size) // 4
IndexError: list index out of range`

I have 15 Kafka brokers with the following number of Partitions on them:

Broker01: 434
Broker02: 446
Broker03: 444
Broker04: 369
Broker05: 475
Broker06: 445
Broker07: 453
Broker08: 431
Broker09: 431
Broker10: 426
Broker11: 481
Broker12: 415
Broker13: 356
Broker14: 356
Broker15: 392

I could solve the problem by balancing by count in a previous (separated) step, count and size chained together produce the same error.

I should mention that I have to separated kafka data directories (two disks) on each broker, but specifying only one data dir by using '-d' did not help.

**Comment by toddpalino** [comment]
I apologize for not seeing this sooner. Github hasn't been sending up notifications on this project.

There shouldn't be any difference between chaining modules or not - they operate completely separately. This may be a case of the multiple data directories causing issues - you unfortunately will not get a good size balance from this. We don't have that type of config, so my code makes assumptions around it that are not appropriate. The solution to this is to use JMX to get the sizes, but this work is yet to be done.

Looking at the code, the only issue I can think of that would cause an IndexError on this line would be that you have a partition (or partitions) with a number of replicas that is causing an issue. Can you give me an idea of what the replica layout looks like (number of partitions with 1 replica, number with 2, etc.) ?

**Comment by mwol** [comment]
Thank you for your answer and this time I apologize for not replying. I had to work on different things and forgot about this issue, I will come back to you when I have again gathered some information, in the meantime I did some separate rebalancing of the disk partitions which seem to work well enough :)

**Comment by bringhurst** [comment]
Going to close this for now since it doesn't look like we can repro. Please reopen this or create a new issue if you have any more info.
